# Generated by Django 3.0.3 on 2020-03-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('apprentice', 'aprendiz'), ('conscious', 'consciente'), ('saver', 'poupador'), ('investor', 'Investidor'), ('master', 'investidor mestre')], max_length=20)),
                ('number', models.IntegerField()),
                ('question_number', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('answers', models.ManyToManyField(related_name='answers', to='question.Answer')),
            ],
            options={
                'verbose_name': 'Nível',
                'verbose_name_plural': 'Níveis',
            },
        ),
    ]
