# Generated by Django 3.0.3 on 2020-03-18 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20200318_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Resposta', 'verbose_name_plural': 'Respostas'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name': 'Fase', 'verbose_name_plural': 'Fases'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='é a resposta certa?'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='question.Level', verbose_name='Respostas'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='order',
            field=models.PositiveIntegerField(verbose_name='ordem'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=140, verbose_name='resposta'),
        ),
        migrations.AlterField(
            model_name='level',
            name='description',
            field=models.CharField(max_length=200, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.CharField(choices=[('apprentice', 'aprendiz'), ('conscious', 'consciente'), ('saver', 'poupador'), ('investor', 'Investidor'), ('master', 'investidor mestre')], max_length=20, verbose_name='nível'),
        ),
        migrations.AlterField(
            model_name='level',
            name='number',
            field=models.PositiveIntegerField(verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='level',
            name='question_number',
            field=models.PositiveIntegerField(verbose_name='número de questões'),
        ),
    ]
