# Generated by Django 3.0.3 on 2020-03-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20200318_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, to='question.Question'),
        ),
    ]
