# Generated by Django 3.0.3 on 2020-03-18 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_level_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='question.Question', verbose_name='Questão'),
        ),
        migrations.AlterField(
            model_name='level',
            name='questions',
            field=models.ManyToManyField(blank=True, to='question.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, max_length=30, verbose_name='título'),
        ),
    ]
